# fly.toml app configuration file generated for damp-dream-194 on 2023-06-29T10:41:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-dream-194"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
